---
- name: Deploy application
  hosts: tag_Environment_Testing
  become: yes
  gather_facts: no
  tasks:
    - name: Copy app systemd file to /etc/systemd/system
      template:
        src: dcmetromap.service
        dest: /etc/systemd/system/dcmetromap.service

    - name: enable and start service
      systemd:
        name: dcmetromap
        daemon_reload: yes
        enabled: yes
        state: started
