--- 
- name: Get info about available AMIs
  hosts: localhost
  connection: local
  tasks:
    - name: get ami info
      amazon.aws.ec2_ami_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ region }}"
        filters:
          name: "RHEL-8*"
      register: AMIs

    - name: print out AMIs
      debug:
        var: AMIs