---
- name: Provision instance to deploy app
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    key_name: aws_key
    region: us-east-2
    image: dunno
    id: "demo-app"
    sec_group: "{{ id }}-sec"
  tasks:
    - name: Get Instance facts 
      block:
        - name: Get Instances facts
          amazon.aws.ec2_instance_facts:
            aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
            aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
            region: "{{ region }}"
          register: result

        - name: Instance id
          debug:
            msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
          loop: "{{ result.instances }}"

      tags: always 

    - name: Provision EC2 Instances
      block:
        - name: Upload public key to AWS 
          amazon.aws.ec2_key:
            name: "{{ key_name }}"
            key_material: ss
            region: "{{ region }}"
            aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
            aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"

        - name: Create security group
          amazon.aws.ec2_group:
            name: "{{ sec_group }}"
            description: "sec group for app {{ id }}"
            region: "{{ region }}"
            aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
            aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
            rules:
              - proto: tcp 
                ports:
                  - 22
                cidr_ip: 0.0.0.0/0
                rule_desc: allow all on ssh port 
          register: result_sec_group

        - name: Provision instance(s)
          amazon.aws.ec2:
            aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
            aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
            key_name: "{{ key_name }}"
            id: "{{ id }}"
            group_id: "{{ result_sec_group.group_id }}"
            image: "{{ image }}"
            instance_type: t2.micro
            region: "{{ region }}"
            wait: true
            count: 1
          
      tags: ['never', 'create_ec2']